const brandArray = [
  'Covergirl',
  'Almay',
  'Anna Sui',
  'Annabelle',
  "Burt's Bees",
  'Butter London',
  'Cargo Cosmetics',
  'China Glaze',
  'Clinique',
  'Dalish',
  'Dr. Hauschka',
  'E.l.f.',
  'Essie',
  "L'Oreal",
  'Marcelle',
  'Maybelline',
  'Milani',
  'Mineral Fusion',
  'Misa',
  'Mistura',
  'Moov',
  'Nyx',
  'Orly',
  'Pacifica',
  'Physicians Formula',
  'Piggy Paint',
  'Pure Anada',
  'Revlon',
  'Salon Perfect',
  'Sante',
  'Sinful Colours',
  'Smashbox',
  'Stila',
  'Suncoat',
  'Wet N Wild',
  'Zorah'
];

export {brandArray};